services:
  immich_machine_learning:
    container_name: "immich_machine_learning"
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    env_file:
      - .env
    extends:
      file: hwaccel.ml.yml
      service: openvino
    ports:
    - "${IMMICH_ML_PORT}:3003"
    volumes:
      - model-cache:/cache
    restart: "unless-stopped"
    healthcheck:
      disable: false

  immich_microservices:
    container_name: "immich_microservices"
    image: "ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}"
    env_file: .env
    extends:
      file: hwaccel.transcoding.yml
      service: vaapi
    user: 1000:100
    environment:
      - "DB_USERNAME=${IMMICH_POSTGRES_USERNAME}"
      - "DB_PASSWORD=${IMMICH_POSTGRES_PASSWORD}"
      - "DB_DATABASE_NAME=${IMMICH_POSTGRES_DATABASE_NAME}"
      - "DB_HOSTNAME=${IMMICH_POSTGRES_HOSTNAME}"
      - "TZ=Asia/Kolkata"
      - "IMMICH_WORKERS_EXCLUDE=api"
      - "REDIS_HOSTNAME=${IMMICH_REDIS_HOSTNAME}"
    volumes:
      - immich-configs-upload:/data/upload
      - immich-configs-profile:/data/profile
      - immich-cache-encoded-video:/data/encoded-video
      - immich-cache-thumbs:/data/thumbs
      - immich-data:/data/library
      - immich-backup-data:/data/backups
    restart: "unless-stopped"
    healthcheck:
      disable: false

volumes:
  model-cache:
  immich-configs-upload:
    driver: local
    driver_opts:
      type: cifs
      device: "//${REQUIEM_SMB_HOSTNAME}/${IMMICH_CACHE}/upload"
      o: "username=${REQUIEM_SMB_USERNAME},password=${REQUIEM_SMB_PASSWORD},uid=1000,gid=100"
  immich-configs-profile:
    driver: local
    driver_opts:
      type: cifs
      device: "//${REQUIEM_SMB_HOSTNAME}/${IMMICH_CONFIGS}/profile"
      o: "addr=requiem,username=${REQUIEM_SMB_USERNAME},password=${REQUIEM_SMB_PASSWORD},uid=1000,gid=100"
  immich-cache-encoded-video:
    driver: local
    driver_opts:
      type: cifs
      device: "//${REQUIEM_SMB_HOSTNAME}/${IMMICH_CACHE}/encoded-video"
      o: "addr=requiem,username=${REQUIEM_SMB_USERNAME},password=${REQUIEM_SMB_PASSWORD},uid=1000,gid=100"
  immich-cache-thumbs:
    driver: local
    driver_opts:
      type: cifs
      device: "//${REQUIEM_SMB_HOSTNAME}/${IMMICH_CACHE}/thumbs"
      o: "addr=requiem,username=${REQUIEM_SMB_USERNAME},password=${REQUIEM_SMB_PASSWORD},uid=1000,gid=100"
  immich-data:
    driver: local
    driver_opts:
      type: cifs
      device: "//${REQUIEM_SMB_HOSTNAME}/${IMMICH_LIBRARY}"
      o: "addr=requiem,username=${REQUIEM_SMB_USERNAME},password=${REQUIEM_SMB_PASSWORD},uid=1000,gid=100"
  immich-backup-data:
    driver: local
    driver_opts:
      type: cifs
      device: "//${REQUIEM_SMB_HOSTNAME}/${IMMICH_BACKUP}"
      o: "addr=requiem,username=${REQUIEM_SMB_USERNAME},password=${REQUIEM_SMB_PASSWORD},uid=1000,gid=100"
