version: "3.6"
services:
  nextcloud:
    container_name: "nextcloud"
    image: "linuxserver/nextcloud:latest"
    env_file: .env
    environment:
      - "PUID=1000"
      - "PGID=100"
      - "TZ=Asia/Kolkata"
    volumes:
      - "${NEXTCLOUD_CONFIGS}/config:/config"
      - "${NEXTCLOUD_CONFIGS}/data:/data"
      - "${NEXTCLOUD_CONFIGS}/php.ini:/etc/php81/php.ini"
      - "${NEXTCLOUD_DATA_TM9K1}:/data/tm9k1/files"
      - "${NEXTCLOUD_DATA_PAPA}:/data/papa/files"
      - "${NEXTCLOUD_DATA_NITYA}:/data/nitya/files"
    networks:
      - "global_docker_network"
      - "nextcloud_network"
    restart: "unless-stopped"

  nextcloud_postgres:
    container_name: "nextcloud_postgres"
    image: "postgres:${POSTGRES_VERSION}"
    env_file: .env
    environment:
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "PUID=1000"
      - "PGID=100"
      - "TZ=Asia/Kolkata"
    volumes:
      - "${POSTGRES_CONFIGS}/init:/docker-entrypoint-initdb.d"
      - "${POSTGRES_CONFIGS}/data:/var/lib/postgresql/data"
    networks:
      - "nextcloud_network"
    restart: "unless-stopped"

  nextcloud_redis:
    container_name: "nextcloud_redis"
    image: "redis:latest"
    environment:
      - "PUID=1000"
      - "PGID=100"
      - "TZ=Asia/Kolkata"
    networks:
      - "nextcloud_network"
    restart: "unless-stopped"

  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    env_file: .env
    environment:
      - "DOMAIN=${VAULTWARDEN_DOMAIN}"
      - "SIGNUPS_ALLOWED=${VAULTWARDEN_SIGNUPS_ALLOWED}"
      - "SHOW_PASSWORD_HINT=${VAULTWARDEN_SHOW_PASSWORD_HINT}"
    volumes:
      - ${VAULTWARDEN_CONFIGS}/data:/data
    networks:
      - "global_docker_network"
    restart: unless-stopped

networks:
  global_docker_network:
    external: "true"
    name: "global_docker_network"
  nextcloud_network:
    name: "nextcloud_network"
