version: "3.6"
services:
  nextcloud:
    container_name: "nextcloud"
    image: "linuxserver/nextcloud:latest"
    env_file: .env
    environment:
      - "PUID=1000"
      - "PGID=100"
      - "TZ=Asia/Kolkata"
    volumes:
      - "${NEXTCLOUD_CONFIGS}/config:/config"
      - "${NEXTCLOUD_CONFIGS}/data:/data"
      - "${NEXTCLOUD_CONFIGS}/php.ini:/etc/php81/php.ini"
      - "${NEXTCLOUD_DATA_TM9K1}:/data/tm9k1/files"
      - "${NEXTCLOUD_DATA_PAPA}:/data/papa/files"
      - "${NEXTCLOUD_DATA_NITYA}:/data/nitya/files"
    networks:
      - "global_docker_network"
      - "nextcloud_network"
    restart: "unless-stopped"

  nextcloud_postgres:
    container_name: "nextcloud_postgres"
    image: "postgres:${NC_POSTGRES_VERSION}"
    env_file: .env
    environment:
      - "POSTGRES_PASSWORD=${NC_POSTGRES_PASSWORD}"
      - "POSTGRES_USER=${NC_POSTGRES_USER}"
      - "PUID=1000"
      - "PGID=100"
      - "TZ=Asia/Kolkata"
    volumes:
      - "${NC_POSTGRES_CONFIGS}/init:/docker-entrypoint-initdb.d"
      - "${NC_POSTGRES_CONFIGS}/data:/var/lib/postgresql/data"
    networks:
      - "nextcloud_network"
    restart: "unless-stopped"

  nextcloud_redis:
    container_name: "nextcloud_redis"
    image: "redis:latest"
    environment:
      - "PUID=1000"
      - "PGID=100"
      - "TZ=Asia/Kolkata"
    networks:
      - "nextcloud_network"
    restart: "unless-stopped"

#######################################################
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#######################################################

  immich_server:
    container_name: "immich_server"
    image: "ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}"
    env_file: .env
    environment:
      - "DB_USERNAME=${IM_POSTGRES_USERNAME}"
      - "DB_PASSWORD=${IM_POSTGRES_PASSWORD}"
      - "DB_DATABASE_NAME=${IM_POSTGRES_DATABASE_NAME}"
      - "DB_HOSTNAME=${IM_POSTGRES_HOSTNAME}"
      - "TZ=Asia/Kolkata"
    user: 1000:100
    command: [ "start.sh", "immich" ]
    volumes:
      - ${IMMICH_CACHE}/upload:/usr/src/app/upload/upload                 # store temp uploads in configs dir (TODO: move to cache)
      - ${IMMICH_CONFIGS}/profile:/usr/src/app/upload/profile             # store profile pics in configs dir
      - ${IMMICH_CACHE}/encoded-video:/usr/src/app/upload/encoded-video   # store thumbs in cache (SSD)
      - ${IMMICH_CACHE}/thumbs:/usr/src/app/upload/thumbs                 # store thumbs in cache (SSD)
      - ${IMMICH_DATA}:/usr/src/app/upload/library                        # store assets on my HDD
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - immich_redis
      - immich_postgres
    networks:
      - "global_docker_network"
      - "immich_network"
    restart: "unless-stopped"

  immich_postgres:
    container_name: "immich_postgres"
    image: "tensorchord/pgvecto-rs:pg14-v0.1.11@sha256:0335a1a22f8c5dd1b697f14f079934f5152eaaa216c09b61e293be285491f8ee"
    env_file: .env
    environment:
      - "POSTGRES_PASSWORD=${IM_POSTGRES_PASSWORD}"
      - "POSTGRES_USER=${IM_POSTGRES_USERNAME}"
      - "POSTGRES_DB=${IM_POSTGRES_DATABASE_NAME}"
      - "PUID=1000"
      - "PGID=100"
      - "TZ=Asia/Kolkata"
    ports:
      - "${IM_POSTGRES_PORT}:5432"
    volumes:
      - "${IM_POSTGRES_CONFIGS}/init:/docker-entrypoint-initdb.d"
      - "${IM_POSTGRES_CONFIGS}/data:/var/lib/postgresql/data"
    networks:
      - "immich_network"
    restart: "unless-stopped"

  immich_redis:
    container_name: "immich_redis"
    image: "redis:6.2-alpine@sha256:afb290a0a0d0b2bd7537b62ebff1eb84d045c757c1c31ca2ca48c79536c0de82"
    env_file: .env
    environment:
      - "PUID=1000"
      - "PGID=100"
      - "TZ=Asia/Kolkata"
    ports:
    - "${IM_REDIS_PORT}:6379"
    networks:
      - "immich_network"
    restart: "unless-stopped"

  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    env_file: .env
    environment:
      - "DOMAIN=${VAULTWARDEN_DOMAIN}"
      - "SIGNUPS_ALLOWED=${VAULTWARDEN_SIGNUPS_ALLOWED}"
      - "SHOW_PASSWORD_HINT=${VAULTWARDEN_SHOW_PASSWORD_HINT}"
    volumes:
      - ${VAULTWARDEN_CONFIGS}/data:/data
    networks:
      - "global_docker_network"
    restart: unless-stopped

#######################################################

volumes:
  model-cache:

networks:
  global_docker_network:
    external: "true"
    name: "global_docker_network"
  nextcloud_network:
    name: "nextcloud_network"
  immich_network:
    name: "immich_network"
