version: "3.6"
services:

  pyload-ng: # download via http
    container_name: "pyload-ng"
    image: lscr.io/linuxserver/pyload-ng:latest
    env_file: .env
    environment:
      - PUID=1000
      - PGID=1000
      - "TZ=Asia/Kolkata"
    volumes:
      - "${PYLOAD_NG_CONFIGS}/config:/config:rw"
      - "${PYLOAD_NG_DOWNLOADS}:/downloads:rw"
    networks:
      - "global_docker_network"
    restart: "unless-stopped"

  qflood:
    container_name: "qflood"
    image: "linuxserver/qbittorrent:latest"
    env_file: .env
    environment:
      - "PUID=1000"
      - "PGID=100"
      - "TZ=Asia/Kolkata"
      - DOCKER_MODS=ghcr.io/vuetorrent/vuetorrent-lsio-mod:latest
    volumes:
      - "${QFLOOD_DOWNLOADS}:/downloads"
      - "${QFLOOD_CONFIGS}/config:/config/qBittorrent"
    networks:
      - "global_docker_network"
    restart: "unless-stopped"

networks:
  global_docker_network:
    external: "true"
    name: "global_docker_network"
