services:
  docker-hoster: # for contacting containers from host wihtout IP
    build:
      context: .
    container_name: "docker-hoster"
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock'
      - '/etc/hosts:/tmp/hosts'
    restart: unless-stopped
