# Hosting my own version of ChatGPT with a text-modal LLM

services:
  open-webui:
    container_name: "open-webui"
    image: "ghcr.io/open-webui/open-webui:main"
    env_file: .env
    environment:
      - "PUID=1000"
      - "PGID=100"
      - "TZ=Asia/Kolkata"
      - "OLLAMA_API_BASE_URL=${OLLAMA_BASE_URL}/api"
      - "WEBUI_NAME=${_CUSTOM_NAME}"
      - "WEBUI_URL=${_WEBUI_URL}"
      - "ENABLE_SIGNUP=${_ENABLE_SIGNUP}"
    volumes:
      - "open-webui:/app/backend/data"
    ports:
      -  "3080:8080"
    networks:
      - "llm_network"
    restart: unless-stopped

  ollama:
    container_name: "ollama"
    image: "ollama/ollama"
    env_file: .env
    environment:
      - "TZ=Asia/Kolkata"
    volumes:
      - "${OLLAMA_DATA}:/root/.ollama/models"
    networks:
      - "llm_network"
    restart: unless-stopped

  llm_redis:
    container_name: llm_redis
    image: docker.io/valkey/valkey:8-alpine
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    networks:
      - "llm_network"
    volumes:
      - valkey-data:/data
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    env_file:
      - .env
    restart: unless-stopped
    ports:
      -  "8080:8080"
    networks:
      - "llm_network"
    volumes:
      - ${SEARXNG_CONFIGS}:/etc/searxng:rw
      - searxng-data:/var/cache/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://searxng:8080/
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

volumes:
  open-webui:
  ollama:
  searxng-data:
  valkey-data:

networks:
  llm_network:
    name: "llm_network"
