##################################################################################
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
##################################################################################

services:
  immich_server:
    container_name: "immich_server"
    image: "ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}"
    env_file: .env
    environment:
      DB_USERNAME: ${IM_POSTGRES_USERNAME}
      DB_PASSWORD: ${IM_POSTGRES_PASSWORD}
      DB_DATABASE_NAME: ${IM_POSTGRES_DATABASE_NAME}
      DB_HOSTNAME: ${IM_POSTGRES_HOSTNAME}
      REDIS_HOSTNAME: ${IM_REDIS_HOSTNAME}
      TZ: 'Asia/Kolkata'
      IMMICH_WORKERS_INCLUDE: 'api'
    user: 1000:100
    volumes:
      - ${IMMICH_CACHE}/upload:/usr/src/app/upload/upload
      - ${IMMICH_CONFIGS}/profile:/usr/src/app/upload/profile
      - ${IMMICH_CACHE}/encoded-video:/usr/src/app/upload/encoded-video
      - ${IMMICH_CACHE}/thumbs:/usr/src/app/upload/thumbs
      - ${IMMICH_DATA}:/usr/src/app/upload/library
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - immich_redis
      - immich_postgres
    networks:
      - "global_docker_network"
      - "immich_network"
    restart: "unless-stopped"

  immich_postgres:
    container_name: "immich_postgres"
    image: "registry.hub.docker.com/tensorchord/pgvecto-rs:${IM_POSTGRES_VERSION}"
    env_file: .env
    environment:
      - "POSTGRES_PASSWORD=${IM_POSTGRES_PASSWORD}"
      - "POSTGRES_USER=${IM_POSTGRES_USERNAME}"
      - "POSTGRES_DB=${IM_POSTGRES_DATABASE_NAME}"
      - "PUID=1000"
      - "PGID=100"
      - "TZ=Asia/Kolkata"
    ports:
      - "${TAILSCALE_IP}:${IM_POSTGRES_PORT}:5432"
    volumes:
      - "${IM_POSTGRES_CONFIGS}/init:/docker-entrypoint-initdb.d"
      - "${IM_POSTGRES_CONFIGS}/data:/var/lib/postgresql/data"
    networks:
      - "immich_network"
    restart: "unless-stopped"

  immich_redis:
    container_name: "immich_redis"
    image: "registry.hub.docker.com/library/redis:${IM_REDIS_VERSION}"
    env_file: .env
    environment:
      - "PUID=1000"
      - "PGID=100"
      - "TZ=Asia/Kolkata"
    healthcheck:
      test: redis-cli ping || exit 1
    ports:
      - "${TAILSCALE_IP}:${IM_REDIS_PORT}:6379"
    networks:
      - "immich_network"
    restart: "unless-stopped"

#######################################################

networks:
  global_docker_network:
    external: "true"
    name: "global_docker_network"
  immich_network:
    name: "immich_network"
