services:
  immich_server:
    container_name: "immich_server"
    image: "ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}"
    env_file: .env
    environment:
      DB_USERNAME: ${IMMICH_POSTGRES_USERNAME}
      DB_PASSWORD: ${IMMICH_POSTGRES_PASSWORD}
      DB_DATABASE_NAME: ${IMMICH_POSTGRES_DATABASE_NAME}
      DB_HOSTNAME: ${IMMICH_POSTGRES_HOSTNAME}
      REDIS_HOSTNAME: ${IMMICH_REDIS_HOSTNAME}
      IMMICH_WORKERS_INCLUDE: 'api'
    user: 1000:100
    volumes:
      - ${IMMICH_LIBRARY}:/data/library
      - ${IMMICH_CACHE}/upload:/data/upload
      - ${IMMICH_CACHE}/thumbs:/data/thumbs
      - ${IMMICH_CACHE}/encoded-video:/data/encoded-video
      - ${IMMICH_CONFIGS}/profile:/data/profile
      - ${IMMICH_BACKUP}:/data/backups
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - immich_redis
      - immich_postgres
    networks:
      - "global_docker_network"
    restart: "unless-stopped"
    healthcheck:
      disable: false

  immich_postgres:
    container_name: "immich_postgres"
    image: ghcr.io/immich-app/postgres:${IMMICH_POSTGRES_VERSION}
    env_file: .env
    environment:
      - "POSTGRES_PASSWORD=${IMMICH_POSTGRES_PASSWORD}"
      - "POSTGRES_USER=${IMMICH_POSTGRES_USERNAME}"
      - "POSTGRES_DB=${IMMICH_POSTGRES_DATABASE_NAME}"
    ports:
      - "${IMMICH_POSTGRES_PORT}:5432"
    volumes:
      - "${IMMICH_POSTGRES_CONFIGS}/init:/docker-entrypoint-initdb.d"
      - "${IMMICH_POSTGRES_CONFIGS}/data:/var/lib/postgresql/data"
    restart: "unless-stopped"

  immich_redis:
    container_name: "immich_redis"
    image: "docker.io/valkey/valkey:${IMMICH_REDIS_VERSION}"
    env_file: .env
    healthcheck:
      test: redis-cli ping || exit 1
    ports:
      - "${IMMICH_REDIS_PORT}:6379"
    restart: "unless-stopped"

#######################################################

networks:
  global_docker_network:
    external: "true"
    name: "global_docker_network"

