services:
  stremio-web:
    container_name: "stremio-web"
    build:
      dockerfile: ./Dockerfile.stremio-web
      args:
        - ${STREMIO_WEB_VERSION}
    env_file: .env
    ports:
      - "8181:80"
    environment:
      - "TZ=Asia/Kolkata"
    networks:
      - "global_docker_network"
    restart: unless-stopped

  minidlna-desktop: # for until Jellyfin's DLNA is non-spec
    container_name: mini-dlna
    image: giof71/minidlna
    env_file: .env
    user: "1000:100"
    environment:
      - "TZ=Asia/Kolkata"
      - MINIDLNA_ROOT_CONTAINER=V
      - MINIDLNA_DIR_V_1=/videos/movies
      - MINIDLNA_DIR_V_2=/videos/tvshows
      - MINIDLNA_ENABLE_INOTIFY=${MINIDLNA_ENABLE_INOTIFY}
      - MINIDLNA_FRIENDLY_NAME=${MINIDLNA_NAME}
    volumes:
      - "${JELLYFIN_MOVIES}:/videos/movies"
      - "${JELLYFIN_TVSHOWS}:/videos/tvshows"
      - ${MINIDLNA_CONFIGS}/log:/log
      - ${MINIDLNA_CONFIGS}/db:/db
    network_mode: host
    restart: unless-stopped

  feishin: # listen to music
    container_name: "feishin"
    image: ghcr.io/jeffvli/feishin:latest
    environment:
      - "PUID=1000"
      - "PGID=100"
      - "TZ=Asia/Kolkata"
    networks:
      - "global_docker_network"
    restart: unless-stopped

  navidrome: # organize/ provide music
    container_name: "navidrome"
    build:
      dockerfile: ./Dockerfile.navidrome
      args:
        - ${NAVIDROME_VERSION}
    env_file: .env
    environment:
      - "ND_CONFIGFILE=/navidrome.toml"
      - "XDG_RUNTIME_DIR=/tmp"
    volumes:
      - "${NAVIDROME_CONFIGS}/navidrome.toml:/navidrome.toml:ro"
      - "${NAVIDROME_CONFIGS}/data:/data"
      - "${NAVIDROME_MUSIC}:/music:ro"
      - "/run/user/${NAVIDROME_HOST_USER_ID}/pulse/native:/tmp/pulse/native"
    networks:
      - "global_docker_network"
    restart: unless-stopped

  jellyfin: # watch content
    container_name: "jellyfin"
    image: "linuxserver/jellyfin:latest"
    devices:
      - "/dev/video10:/dev/video10"
      - "/dev/video11:/dev/video11"
      - "/dev/video12:/dev/video12"
    group_add:
      - "122"
    env_file: .env
    environment:
      - "PUID=1000"
      - "PGID=100"
      - "TZ=Asia/Kolkata"
      - "JELLYFIN_PublishedServerUrl=${JELLYFIN_PUBLISHEDSERVERURL}"
      - "DOCKER_MODS=ghcr.io/intro-skipper/intro-skipper-docker-mod"
    volumes:
      - "${JELLYFIN_CONFIGS}:/config"
      - "${JELLYFIN_MOVIES}:/data/movies"
      - "${JELLYFIN_MUSIC}:/data/music"
      - "${JELLYFIN_TVSHOWS}:/data/tvshows"
      - "/opt/vc/lib:/opt/vc/lib"
    networks:
      - "global_docker_network"
    restart: "unless-stopped"

  jellyseerr: # request content
    container_name: jellyseerr
    image: fallenbagel/jellyseerr:latest
    env_file: .env
    environment:
      - "TZ=Asia/Kolkata"
    volumes:
      - ${JELLYSEERR_CONFIGS}:/app/config
    networks:
      - "global_docker_network"
    restart: unless-stopped

networks:
  global_docker_network:
    external: "true"
    name: "global_docker_network"
