services:
  excalidraw:
    container_name: "excalidraw"
    build:
      dockerfile: Dockerfile.excalidraw
      args:
        - ${EXCALIDRAW_DOCKERFILE_VERSION} # select any one from https://github.com/excalidraw/excalidraw/tags
        - ${EXCALIDRAW_DOCKERFILE_NODE_ENV}
        - ${EXCALIDRAW_DOCKEFILE_DOMAIN_NAME}
        - ${EXCALIDRAW_DOCKERFILE_TZ}
    env_file: .env
    networks:
      - "global_docker_network"
    restart: "unless-stopped"

  excalidraw-room:
    container_name: "excalidraw-room"
    build:
      dockerfile: Dockerfile.excalidraw-room
    env_file: .env
    networks:
      - "global_docker_network"
    restart: "unless-stopped"

networks:
  global_docker_network:
    external: "true"
    name: "global_docker_network"
