FROM node:22 AS build
ARG VERSION

WORKDIR /opt
RUN wget https://github.com/excalidraw/excalidraw/archive/refs/tags/v$VERSION.zip -O excalidraw.zip
RUN unzip excalidraw.zip
RUN mv excalidraw-$VERSION node_app

WORKDIR /opt/node_app

ARG TZ
ARG DOMAIN_NAME

ENV PUB_SRV_NAME=draw.$DOMAIN_NAME
# remove this when done exposing over nginx
ENV PUB_SRV_NAME_WS=draw-ws.$DOMAIN_NAME

ENV VITE_APP_BACKEND_V2_GET_URL=https://$PUB_SRV_NAME/api/v2/
ENV VITE_APP_BACKEND_V2_POST_URL=https://$PUB_SRV_NAME/api/v2/post
ENV VITE_APP_WS_SERVER_URL=https://$PUB_SRV_NAME_WS

RUN yarn --network-timeout 600000

ARG NODE_ENV
RUN yarn build:app:docker

FROM nginx:1.27-alpine-slim
COPY --from=build /opt/node_app/excalidraw-app/build /usr/share/nginx/html

HEALTHCHECK CMD wget -q -O /dev/null http://localhost || exit 1
