services:
  prowlarr: # provide torrents
    container_name: "prowlarr"
    image: "lscr.io/linuxserver/prowlarr:latest"
    env_file: .env
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Asia/Kolkata"
    volumes:
      - "${PROWLARR_CONFIGS}:/config"
    ports:
      - ${TAILSCALE_IP}:9696:9696
    restart: "unless-stopped"

