services:
  homeassistant:
    container_name: "homeassistant"
    image: "lscr.io/linuxserver/homeassistant:latest"
    env_file: .env
    environment:
      - "PUID=1000"
      - "PGID=100"
      - "TZ=Asia/Kolkata"
    volumes:
      - "${HOMEASSISTANT_CONFIGS}:/config"
    networks:
      - "global_docker_network"
    restart: "unless-stopped"

  matter-server:
    container_name: matter-server
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    security_opt:
      - apparmor=unconfined
    volumes:
      - "${MATTER_CONFIGS}/data:/data"
      - /run/dbus:/run/dbus:ro
    network_mode: host
    restart: "unless-stopped"

networks:
  global_docker_network:
    external: "true"
    name: "global_docker_network"
