# wget https://github.com/jagrosh/MusicBot/releases/latest/JMusicBot.jar -O JMusicBot.jar

services:
  jmusicbot:
    build:
      dockerfile: jmusicbot.Dockerfile
      context: .
    container_name: "jmusicbot"
    env_file: .env
    user: 1000:100
    volumes:
      - "${JMUSICBOT_CONFIGS}/:/opt/"
      - "${JMUSICBOT_LOCAL}:/opt/music"
    restart: unless-stopped
    healthcheck:
      test: "[ `pgrep java` -eq 1 ]"
      timeout: 10s
      interval: 1m
      retries: 3
      start_period: 10s
    networks:
      - "backend_network"

networks:
  backend_network:
    name: "backend_network"