version: "3.6"
services:
  stremio-web:
    container_name: "stremio-web"
    build:
      dockerfile: ./Dockerfile.stremio-web
      args:
        - ${STREMIO_WEB_VERSION}
    env_file: .env
    ports:
      - "8181:80"
    environment:
      - "TZ=Asia/Kolkata"
    networks:
      - "global_docker_network"
    restart: unless-stopped

  stremio-service:
    container_name: "stremio-service"
    image: "stremio/server:latest"
    user: "1000:100"
    environment:
      - "TZ=Asia/Kolkata"
    networks:
      - "global_docker_network"
    restart: unless-stopped


networks:
  global_docker_network:
    external: "true"
    name: "global_docker_network"
  # cineris:
  #   external: "true"
  #   name: "cineris"
  #   driver: overlay
