ARG VERSION=latest

FROM tsl0922/ttyd:${VERSION}

RUN apt update && apt upgrade -y
RUN apt install -y ssh

RUN apt install -y python3 python3-pip
RUN apt install -y python3-venv

# set up a venv
RUN mkdir -p /opt/remote-shell
WORKDIR /opt/remote-shell
RUN python3 -m venv venv
RUN /opt/remote-shell/venv/bin/pip install --upgrade pip
RUN /opt/remote-shell/venv/bin/pip install textual
# copy script to image
COPY remote_shell.py /opt/remote-shell/remote_shell.py



ARG MAGIC_COMMAND=echo "This is a magic command. If you see this, it means the remote shell is working correctly."
ENV MAGIC_COMMAND=${MAGIC_COMMAND}

ARG REMOTE_SHELL_PASSWORD=supersecretpassword
ENV REMOTE_SHELL_PASSWORD=${REMOTE_SHELL_PASSWORD}


ENTRYPOINT ["ttyd", "-W", "-w", "/home/ubuntu", "-p", "7681", "-t", "fontSize=14", "-t", "theme={'background':'#000000'}", "/opt/remote-shell/venv/bin/python", "/opt/remote-shell/remote_shell.py"]
