services:
  dozzle-agent:
    container_name: dozzle-agent
    image: amir20/dozzle:v10
    command: agent
    env_file: .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "7007:7007"
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 5s
      retries: 5
      start_period: 5s
      start_interval: 5s
    restart: "unless-stopped"
