services:
  headscale: # Tailscale Coordination Server
    container_name: "headscale"
    image: "headscale/headscale:${HEADSCALE_VERSION}"
    env_file: .env
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Asia/Kolkata"
    volumes:
      - "${HEADSCALE_CONFIGS}/config:/etc/headscale"
    command: serve
    networks:
      - "global_docker_network"
    restart: "unless-stopped"

  tailscale: # Tailscale Node
    container_name: tailscale
    image: tailscale/tailscale:stable
    env_file: .env
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Asia/Kolkata"
    volumes:
      - "${TAILSCALE_CONFIGS}/data:/var/lib" # State data will be stored in this directory
      - /dev/net/tun:/dev/net/tun # Required for tailscale to work
      - "/lib/modules:/lib/modules"
      - "/run/dbus/system_bus_socket:/run/dbus/system_bus_socket" # required for MagicDNS to work
    cap_add: # Required for tailscale to work
      - net_admin
      - sys_module
    privileged: true
    command: tailscaled
    network_mode: host
    restart: unless-stopped

networks:
  global_docker_network:
    external: "true"
    name: "global_docker_network"
